# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapBet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapBet
  
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'

  target 'SnapBetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SnapBetUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
